# Generated by Django 3.1.3 on 2020-11-08 09:46

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка машины')),
                ('rare', models.IntegerField(verbose_name='Редкость')),
                ('visited', models.BooleanField(verbose_name='Встречалась ли')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='cars')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.car')),
            ],
        ),
    ]
